services:
  mysql8:
    image: mysql:8.0.28
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./docker/mysql8/data:/var/lib/mysql
      - ./docker/mysql8/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
        
  mysql9:
    image: mysql:9.0.0
    container_name: mysql9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./docker/mysql9/data:/var/lib/mysql
      - ./docker/mysql9/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 23306:3306
  postgres16:
    image: postgres:16.2
    container_name: postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./docker/postgres16/data:/var/lib/postgresql/data
      - ./docker/postgres16/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
