services:
  mysql8:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql8-db-store:/var/lib/mysql
    ports:
      - 3306:3306
        
  mysql9:
    image: mysql:9.0.0
    container_name: mysql9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql9-db-store:/var/lib/mysql
    ports:
      - 23306:3306
  postgres16:
    image: postgres:16.2
    container_name: postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - postgresql16-db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  mysql8-db-store:
  mysql9-db-store:
  postgresql16-db-store:
